Repository PubMatic-OpenWrap/prebid-server, pull requests merged in 2022-05, with the labels that each got.

#282 UOE-7610: Codify OW patch
  adapters/pubmatic/pubmatic.go
  adapters/pubmatic/pubmatic_ow.go
  adapters/pubmatic/pubmatic_ow_test.go
  adapters/pubmatic/pubmatic_test.go
  endpoints/events/vtrack.go
  endpoints/events/vtrack_ow.go
  endpoints/events/vtrack_ow_test.go
  endpoints/events/vtrack_test.go
  exchange/exchange.go
  exchange/exchange_ow.go
  exchange/exchange_ow_test.go
  exchange/exchange_test.go
  router/router.go
  router/router_ow.go
  router/router_ow_test.go
  router/router_test.go
Labels: master_merge, prebid-upgrade

#284 UOE-7610: Add upgrade script
  scripts/upgrade-pbs.sh
Labels: master_merge

#278 OTT-495 & OTT-499: Creating bidder requests for content object trans…
  exchange/utils.go
  exchange/utils_pubmatic.go
  exchange/utils_pubmatic_test.go
  openrtb_ext/request.go
Labels: master_merge, DO NOT MERGE

#302 OTT-401 :: Supported price floor feature
  config/config.go
  config/config_test.go
  exchange/exchange.go
  exchange/floors.go
  exchange/floors_test.go
  exchange/utils_ow.go
  exchange/utils_ow_test.go
  floors/enforce.go
  floors/enforce_test.go
  floors/floors.go
  floors/floors_test.go
  floors/rule.go
  floors/rule_test.go
  floors/validate.go
  floors/validate_test.go
  openrtb_ext/floors.go
  openrtb_ext/request.go
Labels: ci_master_merge_strategy_pr

#304 OTT-356: Setting WB=1 for adpod bids for new generate bid id feature
  endpoints/events/vtrack_ow_test.go
  endpoints/openrtb2/ctv_auction.go
  floors/enforce.go
Labels: bug, ci_master_merge_strategy_pr

#306 OTT-478: Added updatedrequest in debug log response to know about floor rule selection
  exchange/exchange.go
  floors/enforce.go
  openrtb_ext/response.go
Labels: ci_master_merge_strategy_pr
